development:
    adapter: 'postgresql'
    host: 'localhost'
    database: 'micro_learning'
    user: 'postgres'
    password: ''

production:
  adapter: 'postgresql'
  encoding: 'unicode'
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>